/**
 * Copy @inkdropapp/mermaid's component stylesheet into the plugin's `styles/`.
 *
 * Inkdrop loads a plugin's stylesheets from its own `styles/` directory, and
 * `ipm publish` tars that directory — node_modules is excluded — so the sheet
 * has to be a real file here rather than an `@import` into the package.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const pluginDir = join(dirname(fileURLToPath(import.meta.url)), '..')

const source = require.resolve('@inkdropapp/mermaid/styles.css')
const destination = join(pluginDir, 'styles', 'mermaid.css')

const banner = '/* Generated by scripts/copy-styles.mjs from @inkdropapp/mermaid. Do not edit. */\n'

mkdirSync(dirname(destination), { recursive: true })
writeFileSync(destination, banner + readFileSync(source, 'utf-8'))

console.info(`copy-styles: ${source} -> ${destination}`)
